SRCS = 	main.cpp
C.O = ${SRCS:.c=.o}

NAME = human
hello
CC = c++
FLAGS = -Wall -Wextra -Werror -std=c++98

all : $(NAME)

$(NAME) :
	$hello(CC) $(FLAGS) $(SRCS) -o $(NAME)

# clean :
# 	rm -f $(C.O)

# fclean : clean
# 	rm -f $(NAME)
hell
# re : fclean all

clean :
	rm -f $(NAME)

re : clean all
